### ISSUE TITLE
MuDirac in Galaxy: improve the name of the events in the history

### ISSUE THREAD

**Issue by leandro-liborio** [muon-spectroscopy-computational-project/mudirac#17]
**Is your feature request related to a problem? Please describe.**

In the command-line version of MuDirac, when a calculation is requested for a given muonic atom -i.e.: O-, If the value of `output` parameter is 1, MuDirac will print only transition rates in the `O.xr.out` file.  If, on the other hand, the value of `output` parameter is 2 the application will also produce the states in separate ASCII files, as well as the transition matrices for each line. These output files of states would be named as`O.K1.out`, ` Au.L2.out` and the transition matrices files will be named as `O.K1-L2.tmat.out` and `O.K1-L3.tmat.out` for the input file O.in.

The history panel after running MuDirac in Galaxy has these names for the events:

![MuDirac-history](https://github.com/muon-spectroscopy-computational-project/mudirac/assets/13729496/f24f493f-88ac-4e73-ac75-a602ec333b15)

**Describe the solution you'd like**
In the history panel, I would like that the 'Output of MuDirac' be named 'O.xr.out', and the other events as 'O.err',   'O.spectrum' and  'O.log'

**Comment by subindev-d** [comment]
Done in the muon galaxy tools
